### ISSUE TITLE
mitmdump: error: unrecognized arguments: --no-upstream-cert --insecure -dd

### ISSUE THREAD

**Issue by HarryF514** [viraja1/mitm_postman#3]
./mitm "example.com" "collection_name"
usage: mitmdump [options] [filter]
mitmdump: error: unrecognized arguments: --no-upstream-cert --insecure -dd

--insecure is deprecated.
Please use `--ssl-insecure` instead.
--no-upstream-cert is deprecated.
Please use `--set upstream_cert=value` instead.
To show all options and their default values use --options

**Comment by viraja1** [comment]
This issue is now resolved. Thanks for reporting it
